### PR TITLE
Add footer to the home page

### LINKED ISSUE #3: Add footer to the home page

### PR DESCRIPTION
**Pull request by illseption**
Added footer to the file home.html
Footer says "Copyright 2017, All Rights Reserved"
Fixes #3

### CODE REVIEW

**Comment by illseption** [comment]
But I did add a footer to home.html and on clicking on it, it does show the footer text.

**Comment by divyam3897** [comment]
You have not done rebase which is the reason for your conflicts.

**Comment by illseption** [comment]
What do I do then? I checked the branches and both say they are up to date.

**Comment by divyam3897** [comment]
Switch to master, change remote to pclub original repo, do git pull, checkout to your branch, do rebase, set remote to your forked repo and push the changes.

**Comment by divyam3897** [comment]
It has been fixed in https://github.com/pclubuiet/website/commit/44e7fdc0bfc83b6f32e9c013a08dda949fcf2f9a Thanks

**Pull request closed without merging**
