### PR TITLE
Mybranch

### PR DESCRIPTION
**Pull request by harshita97**
Fixes issue #91 Add Service Worker

Changes: [service-worker,js file added in template/js and scripts added in the body oh basic.html]

Demo Link: [Add here the link where your changes can be seen]

Screenshots for the change:
capture

### CODE REVIEW

**Comment by divyam3897** [comment]
Are you still working on it @harshita97 ? Can you please remove the not required changes?

**Comment by harshita97** [comment]
yes i am still working on it. I will remove those not required changes

**Comment by harshita97** [comment]
okay

**Comment by divyam3897** [comment]
As it's a duplicate of https://github.com/pclubuiet/website/pull/111 so closing it

**Pull request closed without merging**
