### PR TITLE
Fixed project level urls, and home app urls. Fixes #66

### LINKED ISSUE #66: Make "/" redirect to "/home"
Currently, http://pclubuiet.herokuapp.com/ leads to an error as no view responds to this request. 
The home page is at http://pclubuiet.herokuapp.com/home

Just make the former redirect to the latter.

### PR DESCRIPTION
**Pull request by naman**

### CODE REVIEW

**Comment by gurpreetsingh00885** [comment]
Also do a rebase.

**Comment by gurpreetsingh00885** [comment]
That is what I had in mind too @sagar-kalra

**Comment by sagar-kalra** [comment]
@naman 
Take a look at this https://stackoverflow.com/questions/27886078/django-redirecting-blank-url-to-named-url

**Comment by sagar-kalra** [comment]
@naman  Still working on this?

**Comment by divyam3897** [comment]
Fixed in https://github.com/pclubuiet/website/commit/ce643e1afa7c07424f020cb052211013f0c5728a Thanks

**Pull request closed without merging**
