### PR TITLE
Add image for jumbotron

### PR DESCRIPTION
**Pull request by Loveiswar**
Fixes issue #77 

Changes: The background of the jumbotron is changed. 
                 The title is brought in the center of the jumbotron.

### CODE REVIEW

**Comment by Loveiswar** [comment]
Please review!

**Comment by sagar-kalra** [comment]
Can you please provide the screenshot of the page? @Loveiswar

**Comment by Loveiswar** [comment]
/home/ankur/Downloads/Screenshot-2017-10-7 Screenshot.png

**Comment by Loveiswar** [comment]
screenshot-2017-10-7 screenshot

**Comment by sagar-kalra** [comment]
@gurpreetsingh00885 @divyam3897 Please review this change. Is this what you were looking for?

**Comment by abdullah-K** [comment]
@Loveiswar I think that you haven't started the server in your screenshot, which is why those Django template blocks are showing up. You have to test your commits as well. See the [README.md](https://github.com/pclubuiet/website/blob/master/README.md) file for more details on how to do this.

**Comment by Loveiswar** [comment]
@abdullah-k 
I think that's not the demand of the issue!

**Comment by abdullah-K** [comment]
I understand. You sent me an e-mail asking about this. Please check your inbox, I replied to you explaining this :smile:

**Pull request closed without merging**
