### PR TITLE
home/urls.py: Add urls for home app

### PR DESCRIPTION
**Pull request by sagar-kalra**
Add urls.py for home and change in urls.py for pclubWebsite

Fixes https://github.com/pclubuiet/website/issues/10

### CODE REVIEW

**Comment by sagar-kalra** [comment]
Done. Check it out. @gurpreetsingh00885

**Comment by gurpreetsingh00885** [comment]
Your branch is still 2 commits behind master. 
You need to add a new remote to this repo (not the forked one) and then rebase using it.

**Comment by sagar-kalra** [comment]
I did it. Check it out @gurpreetsingh00885

**Comment by divyam3897** [comment]
It has been merged. Thank you for your PR

**Pull request merged**
