### PR TITLE
Fixes #6

### LINKED ISSUE #6: README.md: Correct directory name for 'cd'
The step after cloning asks the reader to run the following command:

`cd pclubuiet
`

The name of the directory (cloned repo) won't be pclubuiet. It will be 'website'.

### PR DESCRIPTION
**Pull request by ashwani99**

### CODE REVIEW

**Comment by gurpreetsingh00885** [comment]
Looks good to me but the commit message isn't descriptive enough. At least describe what you changed. Amend the message and its ready to be merged.

**Comment by ashwani99** [comment]
@gurpreetsingh00885 Is it good now?

**Comment by gurpreetsingh00885** [comment]
looks good. ready to be merged.
A piece of advice: Never make changes on master branch of your clone. Make a new branch for every issue you work on.

**Comment by gurpreetsingh00885** [comment]
Ready to merge @divyam3897

**Comment by divyam3897** [comment]
your PR is merged, thank you.

**Pull request merged**
