### PR TITLE
Fix #4

### LINKED ISSUE #4: Create a new app "resources"
Add the view i.e a new page for it and also url corresponding to it

### PR DESCRIPTION
**Pull request by FabioRosado**
Hello @divyam3897 I messed up with the rebase so the previous PR got closed and I'm sending you a new one. This one should work.
Sorry about all the hassle!

### CODE REVIEW

**Comment by FabioRosado** [comment]
Sorry @divyam3897 had to get up at 2:40 am for work and made a mistake. 
I've changed it so it should work now. Note that the active link from navbar will remain in Home because I'm just extending home to resources at the moment.

**Comment by FabioRosado** [comment]
Ops! Fixed that issue, I've also changed the navbar so now when you press home it will go back to home instead of # 
Hope this is okay

**Comment by FabioRosado** [comment]
I did say that I was just extending the home.html to resources page and that the navbar wasn't touched yet.
I changed the navbar and now the right active link will show.

**Comment by divyam3897** [comment]
Your PR has been merged, thank you

**Pull request merged**
